name: hydroponic_controller
description: A beautiful hydroponic monitoring and control application with MQTT, notifications, and charts.

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # MQTT Client for communication with ESP32
  mqtt_client: ^10.0.0
  
  # Local Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2
  
  # Charts and Graphs
  fl_chart: ^0.66.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # File System & Permissions
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  
  # Video Player
  video_player: ^2.8.1
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon.png
    - assets/logo.png
    - assets/splash_video.mp4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 