class PlantData {
  final int id;
  final String namaIndonesia;
  final String namaInggris;
  final String kategori;
  final double ecMin;
  final double ecMax;
  final int ppmMin;
  final int ppmMax;
  final String pupukSemai;
  final String pupukVegetatif;
  final String pupukGeneratif;
  final String keterangan;
  final int masaPanenMin;
  final int masaPanenMax;
  final String icon;
  final String color;

  PlantData({
    required this.id,
    required this.namaIndonesia,
    required this.namaInggris,
    required this.kategori,
    required this.ecMin,
    required this.ecMax,
    required this.ppmMin,
    required this.ppmMax,
    required this.pupukSemai,
    required this.pupukVegetatif,
    required this.pupukGeneratif,
    required this.keterangan,
    required this.masaPanenMin,
    required this.masaPanenMax,
    required this.icon,
    required this.color,
  });

  // Convert to/from JSON for storage
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'namaIndonesia': namaIndonesia,
      'namaInggris': namaInggris,
      'kategori': kategori,
      'ecMin': ecMin,
      'ecMax': ecMax,
      'ppmMin': ppmMin,
      'ppmMax': ppmMax,
      'pupukSemai': pupukSemai,
      'pupukVegetatif': pupukVegetatif,
      'pupukGeneratif': pupukGeneratif,
      'keterangan': keterangan,
      'masaPanenMin': masaPanenMin,
      'masaPanenMax': masaPanenMax,
      'icon': icon,
      'color': color,
    };
  }

  factory PlantData.fromJson(Map<String, dynamic> json) {
    return PlantData(
      id: json['id'],
      namaIndonesia: json['namaIndonesia'],
      namaInggris: json['namaInggris'],
      kategori: json['kategori'],
      ecMin: json['ecMin'].toDouble(),
      ecMax: json['ecMax'].toDouble(),
      ppmMin: json['ppmMin'],
      ppmMax: json['ppmMax'],
      pupukSemai: json['pupukSemai'],
      pupukVegetatif: json['pupukVegetatif'],
      pupukGeneratif: json['pupukGeneratif'],
      keterangan: json['keterangan'],
      masaPanenMin: json['masaPanenMin'],
      masaPanenMax: json['masaPanenMax'],
      icon: json['icon'],
      color: json['color'],
    );
  }

  String get masaPanen => '$masaPanenMin-$masaPanenMax hari';
  String get ppmRange => '$ppmMin-$ppmMax PPM';
  String get ecRange => '$ecMin-$ecMax EC';
}

class PlantDatabase {
  static final List<PlantData> plants = [
    // Sayuran Daun (Hijau)
    PlantData(
      id: 1,
      namaIndonesia: 'Bayam',
      namaInggris: 'Spinach',
      kategori: 'Sayuran Daun',
      ecMin: 1.8,
      ecMax: 2.3,
      ppmMin: 1260,
      ppmMax: 1610,
      pupukSemai: '4ml A + 4ml B',
      pupukVegetatif: '5ml A + 5ml B',
      pupukGeneratif: '6ml A + 6ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 40,
      masaPanenMax: 52,
      icon: '🥬',
      color: '4CAF50',
    ),
    PlantData(
      id: 2,
      namaIndonesia: 'Kemangi',
      namaInggris: 'Basil',
      kategori: 'Sayuran Daun',
      ecMin: 1.0,
      ecMax: 1.6,
      ppmMin: 700,
      ppmMax: 1200,
      pupukSemai: '2ml A + 2ml B',
      pupukVegetatif: '3ml A + 3ml B',
      pupukGeneratif: '4ml A + 4ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 54,
      masaPanenMax: 64,
      icon: '🌿',
      color: '4CAF50',
    ),
    PlantData(
      id: 3,
      namaIndonesia: 'Kubis',
      namaInggris: 'Cabbage',
      kategori: 'Sayuran Daun',
      ecMin: 2.5,
      ecMax: 3.0,
      ppmMin: 1750,
      ppmMax: 2100,
      pupukSemai: '5ml A + 5ml B',
      pupukVegetatif: '6ml A + 6ml B',
      pupukGeneratif: '7ml A + 7ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 80,
      masaPanenMax: 100,
      icon: '🥬',
      color: '4CAF50',
    ),
    PlantData(
      id: 4,
      namaIndonesia: 'Sawi',
      namaInggris: 'Pak Choy',
      kategori: 'Sayuran Daun',
      ecMin: 1.5,
      ecMax: 2.0,
      ppmMin: 1050,
      ppmMax: 1400,
      pupukSemai: '3ml A + 3ml B',
      pupukVegetatif: '4ml A + 4ml B',
      pupukGeneratif: '5ml A + 5ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 50,
      masaPanenMax: 80,
      icon: '🥬',
      color: '4CAF50',
    ),
    PlantData(
      id: 5,
      namaIndonesia: 'Selada',
      namaInggris: 'Lettuce',
      kategori: 'Sayuran Daun',
      ecMin: 0.8,
      ecMax: 1.2,
      ppmMin: 560,
      ppmMax: 840,
      pupukSemai: '2ml A + 2ml B',
      pupukVegetatif: '3ml A + 3ml B',
      pupukGeneratif: '4ml A + 4ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 30,
      masaPanenMax: 40,
      icon: '🥬',
      color: '4CAF50',
    ),

    // Sayuran Buah (Merah)
    PlantData(
      id: 6,
      namaIndonesia: 'Cabai',
      namaInggris: 'Pepper',
      kategori: 'Sayuran Buah',
      ecMin: 1.8,
      ecMax: 2.1,
      ppmMin: 1260,
      ppmMax: 1540,
      pupukSemai: '4ml A + 4ml B',
      pupukVegetatif: '5ml A + 5ml B',
      pupukGeneratif: '6ml A + 6ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 60,
      masaPanenMax: 95,
      icon: '🌶️',
      color: 'F44336',
    ),
    PlantData(
      id: 7,
      namaIndonesia: 'Mentimun',
      namaInggris: 'Cucumber',
      kategori: 'Sayuran Buah',
      ecMin: 1.7,
      ecMax: 2.5,
      ppmMin: 1190,
      ppmMax: 1750,
      pupukSemai: '4ml A + 4ml B',
      pupukVegetatif: '5ml A + 5ml B',
      pupukGeneratif: '6ml A + 6ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 55,
      masaPanenMax: 65,
      icon: '🥒',
      color: 'F44336',
    ),
    PlantData(
      id: 8,
      namaIndonesia: 'Terung',
      namaInggris: 'Eggplant',
      kategori: 'Sayuran Buah',
      ecMin: 2.5,
      ecMax: 3.5,
      ppmMin: 1750,
      ppmMax: 2450,
      pupukSemai: '6ml A + 6ml B',
      pupukVegetatif: '7ml A + 7ml B',
      pupukGeneratif: '8ml A + 8ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 100,
      masaPanenMax: 150,
      icon: '🍆',
      color: 'F44336',
    ),
    PlantData(
      id: 9,
      namaIndonesia: 'Tomat',
      namaInggris: 'Tomato',
      kategori: 'Sayuran Buah',
      ecMin: 2.0,
      ecMax: 5.0,
      ppmMin: 1400,
      ppmMax: 3500,
      pupukSemai: '7ml A + 7ml B',
      pupukVegetatif: '9ml A + 9ml B',
      pupukGeneratif: '10ml A + 10ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 80,
      masaPanenMax: 140,
      icon: '🍅',
      color: 'F44336',
    ),

    // Sayuran Umbi (Oranye)
    PlantData(
      id: 10,
      namaIndonesia: 'Bawang',
      namaInggris: 'Onion',
      kategori: 'Sayuran Umbi',
      ecMin: 1.4,
      ecMax: 1.8,
      ppmMin: 980,
      ppmMax: 1260,
      pupukSemai: '2ml A + 2ml B',
      pupukVegetatif: '3ml A + 3ml B',
      pupukGeneratif: '4ml A + 4ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 55,
      masaPanenMax: 70,
      icon: '🧅',
      color: 'FF9800',
    ),
    PlantData(
      id: 11,
      namaIndonesia: 'Lobak',
      namaInggris: 'Radish',
      kategori: 'Sayuran Umbi',
      ecMin: 1.2,
      ecMax: 2.2,
      ppmMin: 840,
      ppmMax: 1540,
      pupukSemai: '3ml A + 3ml B',
      pupukVegetatif: '4ml A + 4ml B',
      pupukGeneratif: '5ml A + 5ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 25,
      masaPanenMax: 30,
      icon: '🥕',
      color: 'FF9800',
    ),
    PlantData(
      id: 12,
      namaIndonesia: 'Wortel',
      namaInggris: 'Carrot',
      kategori: 'Sayuran Umbi',
      ecMin: 1.6,
      ecMax: 2.0,
      ppmMin: 1120,
      ppmMax: 1400,
      pupukSemai: '3ml A + 3ml B',
      pupukVegetatif: '4ml A + 4ml B',
      pupukGeneratif: '5ml A + 5ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 100,
      masaPanenMax: 120,
      icon: '🥕',
      color: 'FF9800',
    ),
    PlantData(
      id: 13,
      namaIndonesia: 'Kentang',
      namaInggris: 'Potato',
      kategori: 'Sayuran Umbi',
      ecMin: 2.0,
      ecMax: 2.5,
      ppmMin: 1400,
      ppmMax: 1740,
      pupukSemai: '4ml A + 4ml B',
      pupukVegetatif: '5ml A + 5ml B',
      pupukGeneratif: '6ml A + 6ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 150,
      masaPanenMax: 190,
      icon: '🥔',
      color: 'FF9800',
    ),

    // Sayuran Batang (Abu-abu)
    PlantData(
      id: 14,
      namaIndonesia: 'Asparagus',
      namaInggris: 'Asparagus',
      kategori: 'Sayuran Batang',
      ecMin: 1.4,
      ecMax: 1.8,
      ppmMin: 980,
      ppmMax: 1260,
      pupukSemai: '2ml A + 2ml B',
      pupukVegetatif: '3ml A + 3ml B',
      pupukGeneratif: '4ml A + 4ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 240,
      masaPanenMax: 270,
      icon: '🌱',
      color: '9E9E9E',
    ),
    PlantData(
      id: 15,
      namaIndonesia: 'Kailan',
      namaInggris: 'Gailan',
      kategori: 'Sayuran Batang',
      ecMin: 1.5,
      ecMax: 2.0,
      ppmMin: 1050,
      ppmMax: 1400,
      pupukSemai: '3ml A + 3ml B',
      pupukVegetatif: '4ml A + 4ml B',
      pupukGeneratif: '5ml A + 5ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 45,
      masaPanenMax: 50,
      icon: '🥬',
      color: '9E9E9E',
    ),
    PlantData(
      id: 16,
      namaIndonesia: 'Seledri',
      namaInggris: 'Celery',
      kategori: 'Sayuran Batang',
      ecMin: 1.8,
      ecMax: 2.4,
      ppmMin: 1260,
      ppmMax: 1680,
      pupukSemai: '4ml A + 4ml B',
      pupukVegetatif: '5ml A + 5ml B',
      pupukGeneratif: '6ml A + 6ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 60,
      masaPanenMax: 90,
      icon: '🌿',
      color: '9E9E9E',
    ),

    // Sayuran Bunga (Biru)
    PlantData(
      id: 17,
      namaIndonesia: 'Bunga Kol',
      namaInggris: 'Cauliflower',
      kategori: 'Sayuran Bunga',
      ecMin: 1.5,
      ecMax: 2.0,
      ppmMin: 1050,
      ppmMax: 1400,
      pupukSemai: '3ml A + 3ml B',
      pupukVegetatif: '4ml A + 4ml B',
      pupukGeneratif: '5ml A + 5ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 85,
      masaPanenMax: 130,
      icon: '🥦',
      color: '2196F3',
    ),
    PlantData(
      id: 18,
      namaIndonesia: 'Brokoli',
      namaInggris: 'Broccoli',
      kategori: 'Sayuran Bunga',
      ecMin: 2.8,
      ecMax: 3.5,
      ppmMin: 1960,
      ppmMax: 2450,
      pupukSemai: '6ml A + 6ml B',
      pupukVegetatif: '7ml A + 7ml B',
      pupukGeneratif: '8ml A + 8ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 100,
      masaPanenMax: 150,
      icon: '🥦',
      color: '2196F3',
    ),

    // Buah Merambat (Ungu)
    PlantData(
      id: 19,
      namaIndonesia: 'Anggur',
      namaInggris: 'Grape',
      kategori: 'Buah Merambat',
      ecMin: 0.8,
      ecMax: 1.5,
      ppmMin: 560,
      ppmMax: 1000,
      pupukSemai: '1ml A + 1ml B',
      pupukVegetatif: '2ml A + 2ml B',
      pupukGeneratif: '3ml A + 3ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 105,
      masaPanenMax: 110,
      icon: '🍇',
      color: '9C27B0',
    ),
    PlantData(
      id: 20,
      namaIndonesia: 'Stroberi',
      namaInggris: 'Strawberry',
      kategori: 'Buah Merambat',
      ecMin: 1.2,
      ecMax: 2.1,
      ppmMin: 840,
      ppmMax: 1540,
      pupukSemai: '3ml A + 3ml B',
      pupukVegetatif: '4ml A + 4ml B',
      pupukGeneratif: '5ml A + 5ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 60,
      masaPanenMax: 120,
      icon: '🍓',
      color: '9C27B0',
    ),
    PlantData(
      id: 21,
      namaIndonesia: 'Semangka',
      namaInggris: 'Water Melon',
      kategori: 'Buah Merambat',
      ecMin: 1.6,
      ecMax: 2.0,
      ppmMin: 1120,
      ppmMax: 1400,
      pupukSemai: '3ml A + 3ml B',
      pupukVegetatif: '4ml A + 4ml B',
      pupukGeneratif: '5ml A + 5ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 70,
      masaPanenMax: 100,
      icon: '🍉',
      color: '9C27B0',
    ),
    PlantData(
      id: 22,
      namaIndonesia: 'Melon',
      namaInggris: 'Melon',
      kategori: 'Buah Merambat',
      ecMin: 2.0,
      ecMax: 2.5,
      ppmMin: 1400,
      ppmMax: 1740,
      pupukSemai: '4ml A + 4ml B',
      pupukVegetatif: '5ml A + 5ml B',
      pupukGeneratif: '6ml A + 6ml B',
      keterangan: 'Dilarutkan dalam 1 liter air bersih',
      masaPanenMin: 90,
      masaPanenMax: 100,
      icon: '🍈',
      color: '9C27B0',
    ),
  ];

  static List<String> get categories {
    return plants.map((plant) => plant.kategori).toSet().toList();
  }

  static List<PlantData> getPlantsByCategory(String category) {
    return plants.where((plant) => plant.kategori == category).toList();
  }

  static PlantData? getPlantById(int id) {
    try {
      return plants.firstWhere((plant) => plant.id == id);
    } catch (e) {
      return null;
    }
  }

  static List<PlantData> searchPlants(String query) {
    return plants.where((plant) =>
      plant.namaIndonesia.toLowerCase().contains(query.toLowerCase()) ||
      plant.namaInggris.toLowerCase().contains(query.toLowerCase()) ||
      plant.kategori.toLowerCase().contains(query.toLowerCase())
    ).toList();
  }
}